version: "3"
services:
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl"   
   
  nginx:
    image: nginx:latest
    container_name: nginx    
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - "./app:/var/www/html"
      - "./nginx/config.nginx.replaced:/etc/nginx/conf.d/default.conf"
      - "./certificates:/var/www/certificates"
      
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html